import type { SeedProduct } from './types.js'

/** "Duración: …", "Proyección: …", "Ideal para …": the three bullets of every product. */
function highlights(duration: string, projection: string, occasion: string): string[] {
    return [`Duración: ${duration}`, `Proyección: ${projection}`, `Ideal para ${occasion}`]
}

/** The KaiZen starter catalog (no photos: they are uploaded from the admin). */
export const products: SeedProduct[] = [
    {
        id: 'kz-0001',
        sku: 'KZ-0001',
        slug: 'lattafa-khamrah-edp-100ml',
        name: 'Lattafa Khamrah EDP 100 ml',
        brand: 'lattafa',
        category: 'arabes',
        gender: 'unisex',
        concentration: 'EDP',
        volumeMl: 100,
        price: 45,
        olfactoryFamily: 'Oriental especiada',
        notesTop: ['Canela', 'Nuez moscada', 'Bergamota'],
        notesHeart: ['Dátiles', 'Praliné', 'Tuberosa', 'Mahonial'],
        notesBase: ['Vainilla', 'Haba tonka', 'Benjuí', 'Mirra', 'Akigalawood'],
        description:
            'Un gourmand especiado que evoca el licor de dátiles y la canela tibia. Dulce, cálido y envolvente, deja una estela inolvidable en las noches frescas.',
        highlights: highlights('10 a 12 horas', 'alta', 'noches y ocasiones especiales'),
        tags: ['bestseller'],
        isFeatured: true,
        stock: 18,
        variants: [],
        createdAt: '2026-01-10T12:00:00.000Z',
    },
    {
        id: 'kz-0002',
        sku: 'KZ-0002',
        slug: 'lattafa-yara-edp-100ml',
        name: 'Lattafa Yara EDP 100 ml',
        brand: 'lattafa',
        category: 'mujer',
        gender: 'mujer',
        concentration: 'EDP',
        volumeMl: 100,
        price: 35,
        olfactoryFamily: 'Floral frutal',
        notesTop: ['Orquídea', 'Heliotropo', 'Mandarina'],
        notesHeart: ['Acorde gourmand', 'Frutas tropicales'],
        notesBase: ['Vainilla', 'Almizcle', 'Sándalo'],
        description:
            'Cremosa, dulce y femenina: un abrazo de orquídea y frutas tropicales sobre una base de vainilla suave. La favorita de quienes aman lo delicado.',
        highlights: highlights('6 a 8 horas', 'moderada', 'el día a día y salidas casuales'),
        tags: ['bestseller'],
        isFeatured: true,
        stock: 22,
        variants: [],
        createdAt: '2026-01-12T12:00:00.000Z',
    },
    {
        id: 'kz-0003',
        sku: 'KZ-0003',
        slug: 'lattafa-asad-edp-100ml',
        name: 'Lattafa Asad EDP 100 ml',
        brand: 'lattafa',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 30,
        olfactoryFamily: 'Ámbar especiada',
        notesTop: ['Pimienta negra', 'Piña', 'Tabaco'],
        notesHeart: ['Café', 'Iris', 'Pachulí'],
        notesBase: ['Ámbar', 'Vainilla', 'Madera seca', 'Benjuí'],
        description:
            'Intenso y seductor, combina pimienta negra y café con un fondo ambarado de vainilla. Una fragancia con carácter para quien no pasa desapercibido.',
        highlights: highlights('8 a 10 horas', 'alta', 'noches de fin de semana'),
        tags: ['nuevo'],
        isFeatured: false,
        stock: 15,
        variants: [],
        createdAt: '2026-03-02T12:00:00.000Z',
    },
    {
        id: 'kz-0004',
        sku: 'KZ-0004',
        slug: 'lattafa-badee-al-oud-oud-for-glory-edp-100ml',
        name: "Lattafa Bade'e Al Oud Oud for Glory EDP 100 ml",
        brand: 'lattafa',
        category: 'unisex',
        gender: 'unisex',
        concentration: 'EDP',
        volumeMl: 100,
        price: 38,
        olfactoryFamily: 'Amaderada',
        notesTop: ['Azafrán', 'Nuez moscada', 'Lavanda'],
        notesHeart: ['Oud', 'Pachulí'],
        notesBase: ['Oud', 'Pachulí', 'Almizcle'],
        description:
            'Oud profundo y azafrán en una composición oscura y elegante. Un perfume de presencia imponente que honra la tradición árabe.',
        highlights: highlights('12 horas o más', 'muy alta', 'eventos formales y clima fresco'),
        tags: [],
        isFeatured: false,
        stock: 0,
        variants: [],
        createdAt: '2026-01-20T12:00:00.000Z',
    },
    {
        id: 'kz-0005',
        sku: 'KZ-0005',
        slug: 'armaf-club-de-nuit-intense-man-edt-105ml',
        name: 'Armaf Club de Nuit Intense Man EDT 105 ml',
        brand: 'armaf',
        category: 'hombre',
        gender: 'hombre',
        concentration: 'EDT',
        volumeMl: 105,
        price: 42,
        compareAtPrice: 52,
        olfactoryFamily: 'Amaderada afrutada',
        notesTop: ['Limón', 'Piña', 'Bergamota', 'Grosella negra', 'Manzana'],
        notesHeart: ['Abedul', 'Jazmín', 'Rosa'],
        notesBase: ['Almizcle', 'Ámbar gris', 'Pachulí', 'Vainilla'],
        description:
            'Piña jugosa y abedul ahumado en una de las fragancias masculinas más celebradas del mundo árabe. Sofisticada, versátil y de gran rendimiento.',
        highlights: highlights('8 a 10 horas', 'alta', 'oficina, citas y eventos'),
        tags: ['bestseller', 'oferta'],
        isFeatured: true,
        stock: 20,
        variants: [],
        createdAt: '2025-12-05T12:00:00.000Z',
    },
    {
        id: 'kz-0006',
        sku: 'KZ-0006',
        slug: 'armaf-club-de-nuit-woman-edp-105ml',
        name: 'Armaf Club de Nuit Woman EDP 105 ml',
        brand: 'armaf',
        category: 'arabes',
        gender: 'mujer',
        concentration: 'EDP',
        volumeMl: 105,
        price: 38,
        olfactoryFamily: 'Chipre floral',
        notesTop: ['Bergamota', 'Naranja', 'Pomelo', 'Durazno'],
        notesHeart: ['Rosa', 'Jazmín', 'Geranio', 'Lichi'],
        notesBase: ['Pachulí', 'Almizcle', 'Vainilla', 'Vetiver'],
        description:
            'Rosa y pachulí con un toque cítrico chispeante: una fragancia chipre moderna, segura de sí misma y muy elegante.',
        highlights: highlights('7 a 9 horas', 'moderada a alta', 'la oficina y cenas'),
        tags: [],
        isFeatured: false,
        stock: 9,
        variants: [],
        createdAt: '2025-12-10T12:00:00.000Z',
    },
    {
        id: 'kz-0007',
        sku: 'KZ-0007',
        slug: 'armaf-club-de-nuit-untold-edp-105ml',
        name: 'Armaf Club de Nuit Untold EDP 105 ml',
        brand: 'armaf',
        category: 'arabes',
        gender: 'unisex',
        concentration: 'EDP',
        volumeMl: 105,
        price: 48,
        olfactoryFamily: 'Ámbar floral',
        notesTop: ['Azafrán', 'Jazmín'],
        notesHeart: ['Ámbar gris', 'Madera ambarada'],
        notesBase: ['Resina de abeto', 'Cedro'],
        description:
            'Azafrán luminoso y maderas ambaradas en una estela cristalina y adictiva. Un aroma de lujo que se siente caro desde el primer toque.',
        highlights: highlights(
            '10 horas o más',
            'alta',
            'cualquier ocasión en la que quieras brillar',
        ),
        tags: ['nuevo'],
        isFeatured: false,
        stock: 7,
        variants: [],
        createdAt: '2026-03-15T12:00:00.000Z',
    },
    {
        id: 'kz-0008',
        sku: 'KZ-0008',
        slug: 'afnan-9pm-edp-100ml',
        name: 'Afnan 9PM EDP 100 ml',
        brand: 'afnan',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 40,
        olfactoryFamily: 'Ámbar vainilla',
        notesTop: ['Manzana', 'Canela', 'Lavanda silvestre', 'Bergamota'],
        notesHeart: ['Flor de azahar', 'Lirio de los valles'],
        notesBase: ['Vainilla', 'Haba tonka', 'Ámbar', 'Pachulí'],
        description:
            'Dulce, especiado y hecho para la noche. Manzana y canela abren paso a una base de vainilla y haba tonka que atrae miradas en cada salida.',
        highlights: highlights('8 a 10 horas', 'alta', 'fiestas y salidas nocturnas'),
        tags: ['bestseller'],
        isFeatured: true,
        stock: 25,
        variants: [],
        createdAt: '2025-11-28T12:00:00.000Z',
    },
    {
        id: 'kz-0009',
        sku: 'KZ-0009',
        slug: 'afnan-supremacy-not-only-intense-extrait-100ml',
        name: 'Afnan Supremacy Not Only Intense Extrait 100 ml',
        brand: 'afnan',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EXTRAIT',
        volumeMl: 100,
        price: 55,
        olfactoryFamily: 'Chipre afrutada',
        notesTop: ['Bergamota', 'Manzana', 'Grosella negra'],
        notesHeart: ['Pachulí', 'Abedul', 'Musgo de roble'],
        notesBase: ['Almizcle', 'Ámbar gris'],
        description:
            'Concentración extrait para una estela poderosa: frutas frescas sobre un corazón ahumado de abedul y musgo. Elegancia que dura todo el día.',
        highlights: highlights('12 horas o más', 'muy alta', 'reuniones importantes y eventos'),
        tags: [],
        isFeatured: false,
        stock: 5,
        variants: [],
        createdAt: '2026-02-01T12:00:00.000Z',
    },
    {
        id: 'kz-0010',
        sku: 'KZ-0010',
        slug: 'rasasi-hawas-for-him-edp-100ml',
        name: 'Rasasi Hawas for Him EDP 100 ml',
        brand: 'rasasi',
        category: 'hombre',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 50,
        compareAtPrice: 60,
        olfactoryFamily: 'Aromática acuática',
        notesTop: ['Manzana', 'Bergamota', 'Limón', 'Canela'],
        notesHeart: ['Notas acuáticas', 'Ciruela', 'Flor de azahar', 'Cardamomo'],
        notesBase: ['Ámbar gris', 'Almizcle', 'Pachulí', 'Madera flotante'],
        description:
            'Frescura acuática con un dulzor afrutado que no pasa inadvertido. Un clásico moderno para los días de calor y las noches de playa.',
        highlights: highlights('8 a 10 horas', 'alta', 'clima cálido y verano'),
        tags: ['bestseller', 'oferta'],
        isFeatured: false,
        stock: 12,
        variants: [],
        createdAt: '2025-12-15T12:00:00.000Z',
    },
    {
        id: 'kz-0011',
        sku: 'KZ-0011',
        slug: 'rasasi-hawas-ice-edp-100ml',
        name: 'Rasasi Hawas Ice EDP 100 ml',
        brand: 'rasasi',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 55,
        olfactoryFamily: 'Aromática fresca',
        notesTop: ['Limón siciliano', 'Manzana', 'Bergamota'],
        notesHeart: ['Cardamomo', 'Ciruela', 'Flor de azahar'],
        notesBase: ['Almizcle', 'Ámbar gris', 'Cedro'],
        description:
            'La versión helada de Hawas: cítricos vibrantes y un efecto refrescante que se siente como una brisa marina. Pura energía.',
        highlights: highlights('7 a 9 horas', 'moderada a alta', 'el gimnasio, el día y el calor'),
        tags: ['nuevo'],
        isFeatured: false,
        stock: 8,
        variants: [],
        createdAt: '2026-03-20T12:00:00.000Z',
    },
    {
        id: 'kz-0012',
        sku: 'KZ-0012',
        slug: 'maison-alhambra-baroque-rouge-540-edp-100ml',
        name: 'Maison Alhambra Baroque Rouge 540 EDP 100 ml',
        brand: 'maison-alhambra',
        category: 'unisex',
        gender: 'unisex',
        concentration: 'EDP',
        volumeMl: 100,
        price: 30,
        olfactoryFamily: 'Ámbar floral',
        notesTop: ['Azafrán', 'Jazmín'],
        notesHeart: ['Ámbar gris', 'Madera ambarada'],
        notesBase: ['Resina de abeto', 'Cedro'],
        description:
            'Una interpretación luminosa del ámbar con azafrán y jazmín. Dulce, aireada y magnética: la estela que todos preguntan qué llevas puesto.',
        highlights: highlights('8 a 10 horas', 'alta', 'cualquier momento del día'),
        tags: [],
        isFeatured: false,
        stock: 16,
        variants: [],
        createdAt: '2026-02-10T12:00:00.000Z',
    },
    {
        id: 'kz-0013',
        sku: 'KZ-0013',
        slug: 'maison-alhambra-salvo-edp-100ml',
        name: 'Maison Alhambra Salvo EDP 100 ml',
        brand: 'maison-alhambra',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 25,
        compareAtPrice: 32,
        olfactoryFamily: 'Aromática fougère',
        notesTop: ['Bergamota', 'Pimienta'],
        notesHeart: ['Lavanda', 'Geranio', 'Pimienta de Sichuan'],
        notesBase: ['Ambroxan', 'Cedro', 'Ládano'],
        description:
            'Fresco, especiado y muy masculino. Bergamota jugosa y ambroxan en una fragancia versátil que funciona de la mañana a la noche.',
        highlights: highlights('6 a 8 horas', 'moderada', 'la oficina y el uso diario'),
        tags: ['oferta'],
        isFeatured: false,
        stock: 0,
        variants: [],
        createdAt: '2026-02-14T12:00:00.000Z',
    },
    {
        id: 'kz-0014',
        sku: 'KZ-0014',
        slug: 'al-haramain-amber-oud-gold-edition-edp',
        name: 'Al Haramain Amber Oud Gold Edition EDP',
        brand: 'al-haramain',
        category: 'arabes',
        gender: 'unisex',
        concentration: 'EDP',
        volumeMl: 60,
        price: 45,
        olfactoryFamily: 'Ámbar dulce',
        notesTop: ['Bergamota', 'Notas verdes'],
        notesHeart: ['Melón', 'Piña', 'Ámbar'],
        notesBase: ['Almizcle', 'Vainilla', 'Madera'],
        description:
            'Ámbar dorado con un toque frutal de melón y piña. Dulce y sofisticado, con una proyección que llena cualquier espacio.',
        highlights: highlights('12 horas o más', 'muy alta', 'eventos y noches especiales'),
        tags: [],
        isFeatured: false,
        stock: 16,
        variants: [
            { id: 'kz-0014-60', label: '60 ml', priceDelta: 0, volumeMl: 60, stock: 6 },
            { id: 'kz-0014-120', label: '120 ml', priceDelta: 20, volumeMl: 120, stock: 10 },
        ],
        createdAt: '2026-01-25T12:00:00.000Z',
    },
    {
        id: 'kz-0015',
        sku: 'KZ-0015',
        slug: 'al-haramain-laventure-edp-100ml',
        name: "Al Haramain L'Aventure EDP 100 ml",
        brand: 'al-haramain',
        category: 'arabes',
        gender: 'hombre',
        concentration: 'EDP',
        volumeMl: 100,
        price: 42,
        olfactoryFamily: 'Cítrica amaderada',
        notesTop: ['Limón', 'Bergamota', 'Grosella negra'],
        notesHeart: ['Pachulí', 'Abedul', 'Jazmín'],
        notesBase: ['Almizcle', 'Ámbar gris', 'Vainilla'],
        description:
            'Cítricos brillantes y un corazón ahumado para el hombre aventurero. Fresca, elegante y con excelente fijación.',
        highlights: highlights('8 a 10 horas', 'alta', 'el día, la oficina y los viajes'),
        tags: [],
        isFeatured: false,
        stock: 10,
        variants: [],
        createdAt: '2026-02-05T12:00:00.000Z',
    },
    {
        id: 'kz-0016',
        sku: 'KZ-0016',
        slug: 'set-armaf-club-de-nuit-intense-man',
        name: 'Set Armaf Club de Nuit Intense Man',
        brand: 'armaf',
        category: 'sets-regalo',
        gender: 'hombre',
        concentration: 'EDT',
        volumeMl: 105,
        price: 55,
        olfactoryFamily: 'Amaderada afrutada',
        notesTop: ['Limón', 'Piña', 'Bergamota', 'Grosella negra', 'Manzana'],
        notesHeart: ['Abedul', 'Jazmín', 'Rosa'],
        notesBase: ['Almizcle', 'Ámbar gris', 'Pachulí', 'Vainilla'],
        description:
            'Estuche de regalo con el Club de Nuit Intense Man EDT de 105 ml y su desodorante en spray de 200 ml. El obsequio que nunca falla.',
        highlights: highlights('8 a 10 horas', 'alta', 'regalar en cumpleaños y fechas especiales'),
        tags: [],
        isFeatured: false,
        stock: 6,
        variants: [],
        createdAt: '2026-02-20T12:00:00.000Z',
    },
    {
        id: 'kz-0017',
        sku: 'KZ-0017',
        slug: 'set-lattafa-yara',
        name: 'Set Lattafa Yara',
        brand: 'lattafa',
        category: 'sets-regalo',
        gender: 'mujer',
        concentration: 'EDP',
        volumeMl: 100,
        price: 48,
        olfactoryFamily: 'Floral frutal',
        notesTop: ['Orquídea', 'Heliotropo', 'Mandarina'],
        notesHeart: ['Acorde gourmand', 'Frutas tropicales'],
        notesBase: ['Vainilla', 'Almizcle', 'Sándalo'],
        description:
            'Yara EDP de 100 ml acompañada de su bruma corporal de 250 ml en un estuche rosado. Un detalle tierno y femenino, listo para regalar.',
        highlights: highlights(
            '6 a 8 horas',
            'moderada',
            'regalar en el Día de la Madre o aniversarios',
        ),
        tags: ['nuevo'],
        isFeatured: false,
        stock: 4,
        variants: [],
        createdAt: '2026-03-25T12:00:00.000Z',
    },
    {
        id: 'kz-0018',
        sku: 'KZ-0018',
        slug: 'carolina-herrera-good-girl-edp',
        name: 'Carolina Herrera Good Girl EDP',
        brand: 'carolina-herrera',
        category: 'europeos',
        gender: 'mujer',
        concentration: 'EDP',
        volumeMl: 50,
        price: 110,
        olfactoryFamily: 'Oriental floral',
        notesTop: ['Almendra', 'Café', 'Bergamota', 'Limón'],
        notesHeart: ['Tuberosa', 'Jazmín sambac', 'Rosa de Bulgaria', 'Flor de azahar'],
        notesBase: ['Haba tonka', 'Cacao', 'Vainilla', 'Praliné', 'Sándalo'],
        description:
            'El icónico tacón de Carolina Herrera: tuberosa y jazmín luminosos sobre cacao y haba tonka. Dualidad entre lo dulce y lo atrevido.',
        highlights: highlights('8 a 10 horas', 'alta', 'noches, citas y celebraciones'),
        tags: ['bestseller'],
        isFeatured: true,
        stock: 14,
        variants: [
            { id: 'kz-0018-50', label: '50 ml', priceDelta: 0, volumeMl: 50, stock: 6 },
            { id: 'kz-0018-80', label: '80 ml', priceDelta: 25, volumeMl: 80, stock: 8 },
        ],
        createdAt: '2025-11-15T12:00:00.000Z',
    },
    {
        id: 'kz-0019',
        sku: 'KZ-0019',
        slug: 'carolina-herrera-212-vip-men-edt-100ml',
        name: 'Carolina Herrera 212 VIP Men EDT 100 ml',
        brand: 'carolina-herrera',
        category: 'europeos',
        gender: 'hombre',
        concentration: 'EDT',
        volumeMl: 100,
        price: 95,
        compareAtPrice: 115,
        olfactoryFamily: 'Amaderada especiada',
        notesTop: ['Lima', 'Pimienta', 'Menta', 'Maracuyá'],
        notesHeart: ['Ginebra', 'Jengibre', 'Vodka helado'],
        notesBase: ['Cuero', 'Madera', 'Ámbar'],
        description:
            'La fragancia de la fiesta exclusiva: un cóctel helado de ginebra y lima sobre maderas y cuero. Para el que siempre está en la lista VIP.',
        highlights: highlights('7 a 9 horas', 'moderada a alta', 'fiestas y vida nocturna'),
        tags: ['oferta'],
        isFeatured: false,
        stock: 4,
        variants: [],
        createdAt: '2025-12-20T12:00:00.000Z',
    },
    {
        id: 'kz-0020',
        sku: 'KZ-0020',
        slug: 'dior-sauvage-edt',
        name: 'Dior Sauvage EDT',
        brand: 'dior',
        category: 'europeos',
        gender: 'hombre',
        concentration: 'EDT',
        volumeMl: 60,
        price: 120,
        olfactoryFamily: 'Aromática fougère',
        notesTop: ['Bergamota de Calabria', 'Pimienta'],
        notesHeart: ['Pimienta de Sichuan', 'Lavanda', 'Geranio', 'Elemí'],
        notesBase: ['Ambroxan', 'Cedro', 'Ládano'],
        description:
            'Fresco, crudo y noble a la vez. La bergamota de Calabria y el ambroxan crean una estela magnética que se convirtió en un clásico instantáneo.',
        highlights: highlights('7 a 9 horas', 'alta', 'cualquier ocasión, de día o de noche'),
        tags: ['bestseller'],
        isFeatured: true,
        stock: 14,
        variants: [
            { id: 'kz-0020-60', label: '60 ml', priceDelta: 0, volumeMl: 60, stock: 5 },
            { id: 'kz-0020-100', label: '100 ml', priceDelta: 30, volumeMl: 100, stock: 9 },
        ],
        createdAt: '2025-11-20T12:00:00.000Z',
    },
    {
        id: 'kz-0021',
        sku: 'KZ-0021',
        slug: 'dior-jadore-edp-100ml',
        name: "Dior J'adore EDP 100 ml",
        brand: 'dior',
        category: 'europeos',
        gender: 'mujer',
        concentration: 'EDP',
        volumeMl: 100,
        price: 150,
        olfactoryFamily: 'Floral',
        notesTop: ['Pera', 'Melón', 'Bergamota'],
        notesHeart: ['Jazmín', 'Rosa', 'Lirio de los valles', 'Ylang-ylang'],
        notesBase: ['Almizcle', 'Vainilla', 'Cedro'],
        description:
            'Un ramo floral absoluto, dorado y sensual. Jazmín, rosa e ylang-ylang en la fragancia emblema de la feminidad según Dior.',
        highlights: highlights('8 a 10 horas', 'moderada a alta', 'eventos elegantes y bodas'),
        tags: [],
        isFeatured: false,
        stock: 3,
        variants: [],
        createdAt: '2026-01-05T12:00:00.000Z',
    },
    {
        id: 'kz-0022',
        sku: 'KZ-0022',
        slug: 'versace-eros-edt-100ml',
        name: 'Versace Eros EDT 100 ml',
        brand: 'versace',
        category: 'europeos',
        gender: 'hombre',
        concentration: 'EDT',
        volumeMl: 100,
        price: 85,
        compareAtPrice: 100,
        olfactoryFamily: 'Aromática fougère',
        notesTop: ['Menta', 'Manzana verde', 'Limón'],
        notesHeart: ['Haba tonka', 'Ambroxan', 'Geranio'],
        notesBase: ['Vainilla de Madagascar', 'Vetiver', 'Cedro', 'Musgo de roble'],
        description:
            'Inspirado en el dios griego del amor: menta fresca y manzana verde sobre una base vibrante de vainilla. Seductor y lleno de energía.',
        highlights: highlights('7 a 9 horas', 'alta', 'citas, fiestas y clima fresco'),
        tags: ['bestseller', 'oferta'],
        isFeatured: false,
        stock: 14,
        variants: [],
        createdAt: '2025-12-01T12:00:00.000Z',
    },
    {
        id: 'kz-0023',
        sku: 'KZ-0023',
        slug: 'versace-bright-crystal-edt-90ml',
        name: 'Versace Bright Crystal EDT 90 ml',
        brand: 'versace',
        category: 'mujer',
        gender: 'mujer',
        concentration: 'EDT',
        volumeMl: 90,
        price: 80,
        olfactoryFamily: 'Floral frutal',
        notesTop: ['Yuzu', 'Granada', 'Notas heladas'],
        notesHeart: ['Peonía', 'Magnolia', 'Flor de loto'],
        notesBase: ['Almizcle', 'Caoba', 'Ámbar'],
        description:
            'Fresca, luminosa y delicadamente floral. Granada y peonía en una fragancia ligera que acompaña con elegancia de la mañana a la noche.',
        highlights: highlights('5 a 7 horas', 'moderada', 'el día a día y la primavera'),
        tags: [],
        isFeatured: false,
        stock: 11,
        variants: [],
        createdAt: '2026-01-18T12:00:00.000Z',
    },
    {
        id: 'kz-0024',
        sku: 'KZ-0024',
        slug: 'jean-paul-gaultier-le-male-elixir-parfum-125ml',
        name: 'Jean Paul Gaultier Le Male Elixir Parfum 125 ml',
        brand: 'jean-paul-gaultier',
        category: 'europeos',
        gender: 'hombre',
        concentration: 'PARFUM',
        volumeMl: 125,
        price: 160,
        olfactoryFamily: 'Ámbar fougère',
        notesTop: ['Lavanda', 'Menta'],
        notesHeart: ['Vainilla', 'Benjuí'],
        notesBase: ['Miel', 'Haba tonka', 'Tabaco'],
        description:
            'La versión más intensa del marinero de Gaultier: lavanda y miel sobre tabaco y haba tonka. Adictivo, cálido y de una fijación impresionante.',
        highlights: highlights('12 horas o más', 'muy alta', 'noches frías y eventos especiales'),
        tags: ['nuevo'],
        isFeatured: false,
        stock: 6,
        variants: [],
        createdAt: '2026-04-01T12:00:00.000Z',
    },
]
