import { feminine, masculine } from '../../common/validation/messages.js'

/** Spanish names of the product fields, used to build validation messages. */
export const FIELD = {
    slug: masculine('El slug'),
    name: masculine('El nombre'),
    category: feminine('La categoría'),
    price: masculine('El precio'),
    compareAtPrice: masculine('El precio anterior'),
    brand: feminine('La marca'),
    brands: feminine('La lista de marcas'),
    gender: masculine('El género'),
    concentration: feminine('La concentración'),
    volumeMl: masculine('El volumen (ml)'),
    notesTop: feminine('La lista de notas de salida'),
    notesHeart: feminine('La lista de notas de corazón'),
    notesBase: feminine('La lista de notas de fondo'),
    olfactoryFamily: feminine('La familia olfativa'),
    isFeatured: masculine('El indicador de destacado'),
    sku: masculine('El SKU'),
    description: feminine('La descripción'),
    highlights: feminine('La lista de destacados'),
    tags: feminine('La lista de etiquetas'),
    rating: feminine('La valoración'),
    reviewCount: feminine('La cantidad de reseñas'),
    stock: masculine('El stock'),
    isActive: masculine('El estado activo'),
    variants: feminine('La lista de variantes'),
    variantLabel: feminine('La etiqueta de la variante'),
    variantPriceDelta: feminine('La diferencia de precio de la variante'),
    variantVolumeMl: masculine('El volumen (ml) de la variante'),
    variantStock: masculine('El stock de la variante'),
    variantId: masculine('El identificador de la variante'),
    search: feminine('La búsqueda'),
    sort: masculine('El orden'),
    minPrice: masculine('El precio mínimo'),
    maxPrice: masculine('El precio máximo'),
    page: feminine('La página'),
    pageSize: masculine('El tamaño de página'),
    limit: masculine('El límite'),
    productId: masculine('El producto'),
    availabilityItems: feminine('La lista de productos'),
} as const
